-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, I.GENDER, COUNT(DISTINCT O.USER_ID) USERS
FROM USER_INFO I
JOIN ONLINE_SALE O
ON O.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), I.GENDER
ORDER BY 1,2,3
