-- 코드를 작성해주세요
SELECT I2.ITEM_ID, I2.ITEM_NAME, I2.RARITY
FROM ITEM_TREE T1
JOIN ITEM_INFO I1
ON T1.ITEM_ID = I1.ITEM_ID
JOIN ITEM_TREE T2
ON T2.PARENT_ITEM_ID = T1.ITEM_ID
JOIN ITEM_INFO I2
ON I2.ITEM_ID = T2.ITEM_ID
WHERE I1.RARITY = 'RARE'
ORDER BY I2.ITEM_ID DESC