-- 코드를 작성해주세요
SELECT I2.ITEM_ID, I3.ITEM_NAME, I3.RARITY
FROM ITEM_TREE I1
JOIN ITEM_INFO I4 ON I4.ITEM_ID = I1.ITEM_ID
JOIN ITEM_TREE I2 ON I2.PARENT_ITEM_ID = I1.ITEM_ID
JOIN ITEM_INFO I3 ON I3.ITEM_ID = I2.ITEM_ID
WHERE I4.RARITY = 'RARE'
ORDER BY I2.ITEM_ID DESC
