-- 코드를 작성해주세요
SELECT SUM(SCORE) SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E
ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G
ON G.EMP_NO = E.EMP_NO
WHERE YEAR = 2022
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1